#!/usr/bin/env bash
# internet (ask wireless or ethernet)
# partition
echo " -- PARTITIONING DISK -- "
parted -a optimal /dev/sda mklabel gpt
parted -a optimal /dev/sda mkpart primary fat32 1MiB 501MiB
parted -a optimal /dev/sda set 1 esp on
parted -a optimal /dev/sda mkpart primary ext4 501MiB 20501MiB
parted -a optimal /dev/sda mkpart primary ext4 20501MiB 100%
mkfs.vfat -F32 /dev/sda1
mkfs.ext4 /dev/sda2
mkfs.ext4 /dev/sda3
# mount partition
echo " -- MOUNTING PARTITIONS -- "
mount /dev/sda2 /mnt
mkdir -p /mnt/boot/efi
mount /dev/sda1 /mnt/boot/efi
mkdir -p /mnt/home
mount /dev/sda3 /mnt/home
# update keyring
pacman -Sy archlinux-keyring --noconfirm
# install the system
echo " -- INSTALLING THE SYSTEM -- "
pacstrap /mnt base linux linux-firmware
# basic configuration of new system
genfstab -U /mnt >/mnt/etc/fstab
mv ins2 /mnt/
chmod +x /mnt/ins2
